macro(getMemoryLeakType type)
  if (WIN32)
    set(${type} "Win32")
  elseif(UNIX)
    set(${type} "Gcc")
  elseif(SYMBIAN)
    set(${type} "Symbian")
  else()
    set(${type} "Starter")
  endif()
endmacro()
