macro(getMemoryLeakType type)
  if (WIN32)
    set(${type} "Win32")
  elseif(UNIX)
    set(${type} "Gcc")
  elseif(SYMBIAN)
    set(${type} "Symbian")
  else()
    set(${type} "Starter")
  endif()
endmacro()

macro(getLibraryType isStatic type)
  if (${isStatic})
      set(${type} STATIC)
  else()
      set(${type} SHARED)
  endif()
endmacro()